nitransforms/linear.py, nitransforms/tests/test_base.py, nitransforms/tests/test_io.py, nitransforms/tests/test_transform.py
bump up testing coverage, mainly for `base` and `linear` modules.
also adds a missing assertion for LTA test.
=> enh: increase coverage

nitransforms/base.py, nitransforms/conftest.py, nitransforms/linear.py, nitransforms/nonlinear.py, nitransforms/tests/test_base.py, nitransforms/tests/test_io.py, nitransforms/tests/test_transform.py
Includes a draft implementation of #22.
=> ENH: Uber-refactor of code style, method names, etc.

.travis.yml
- Adds docker build with fmriprep's software tools to build matrix
Builds are about ~10 minutes, which isn't too bad. 
Might want to save image to cache for easier load.
=> enh+tst: add docker build to travis matrix

nitransforms/base.py, nitransforms/tests/test_linear.py
Setting up the infrastructure to allow the `+` operator, indexed transforms, etc.
This will also set up a base for the storage of transform chains.
This PR completes the requirements promised in the preprint.
=> ENH: Base implementation of transforms chains (composition)

nitransforms/nonlinear.py, nitransforms/tests/test_nonlinear.py
adds `load` functionality for nonlinear transforms similar to linear.
Will need to be revised once `BSplineFieldTransform` is re-added
=> enh: facilitate displacementsfield transform loading

nitransforms/base.py, nitransforms/cli.py, nitransforms/tests/test_cli.py, setup.cfg
Closes #48 
Adds `nt` executable for command line usage of nitransforms.
Currently only supports `nt apply`, which applies a linear or nonlinear transform to an image.
=> ENH: command line interface

.travis.yml, nitransforms/tests/test_linear.py
Tests are passing locally, but a bit iffy on the results.
=> ENH: Add FS transform regression

nitransforms/linear.py, nitransforms/manip.py, nitransforms/tests/test_base.py, nitransforms/tests/test_linear.py, nitransforms/tests/test_manip.py
This PR starts the implementation of "collapsing" series of transforms,
for the linear case.
It is tested on real data added in the context of #66, #74 and #75.
For the moment does not cover unintended use-cases such as collapsing
transform sequences containing one or more nonlinear transforms.
Resolves: #88
=> ENH: Add an ``.asaffine()`` member to ``TransformChain``

CHANGES.rst, nitransforms/__init__.py, nitransforms/io/__init__.py, setup.cfg
Add modules to the ``__init__.py`` of root and ``nitransforms.io`` so
that they are visible for import.
References: #91
=> MAINT: Add imports of modules in ``__init__.py`` to workaround #91

joss/paper.md
Updates the JOSS submission to incorporate the suggestions by @PeerHerholz.
References: openjournals/joss-reviews#3459
Resolves: #119.
=> FIX: Suggested edits to the JOSS submission

docs/index.rst, docs/installation.rst
Adds a new installation section that is missing and required by our JOSS submission.
References: openjournals/joss-reviews#3459
=> DOC: Add an *Installation* section

joss/nt.bib, joss/paper.md
Re: https://github.com/openjournals/joss-reviews/issues/3459#issuecomment-903142434
=> FIX: Add mention to potential alternatives in JOSS submission

CODE_OF_CONDUCT.md
@effigies pinging you as I set you for back-up contact
=> DOC: Transfer CoC from NiBabel

joss/paper.md
Edits to the submission text following @osorensen's suggestions (https://github.com/openjournals/joss-reviews/issues/3459#issuecomment-916088981):
* Add a reference to Figure 1 in the text. Maybe somewhere in the Methods section on page 2?
* Page 3: Add caption to Figure 1.
=> FIX: Final edits to JOSS submission

setup.cfg
RTD is failing because it uses python 3.7.
=> MAINT: scipy-1.8, numpy-1.22 require python 3.8

nitransforms/conftest.py, nitransforms/tests/test_linear.py
Makes the tests less brittle so that they don't fail with FSL 6.0. This doesn't actually address the problems seemingly discovered in FSL 6.0 interpolator (#52), it just raises the bar just enough for tests to pass with FSL 6.0.
=> FIX: Double-check dtypes within tests and increase RMSE tolerance

nitransforms/io/base.py, nitransforms/io/fsl.py, nitransforms/linear.py, nitransforms/tests/test_linear.py
Implements importing series of textfiles (<name>.000, ...) generated by FSL tools (e.g., MCFLIRT).
References: #40.
=> FIX: Load arrays of linear transforms from FSL files

nitransforms/cli.py, nitransforms/io/afni.py, nitransforms/linear.py, nitransforms/tests/test_cli.py, nitransforms/tests/test_linear.py
Implements importing text files with series of transforms generated by `3dVolreg`.
References: #40.
=> FIX: Load arrays of linear transforms from AFNI files

nitransforms/io/fsl.py, nitransforms/nonlinear.py, nitransforms/tests/test_nonlinear.py
=> ENH: I/O of FSL displacements fields

nitransforms/io/base.py, nitransforms/io/itk.py, nitransforms/tests/test_io.py
- Avoid `DeprecationWarning` by not using the `MatFile4Reader`/`MatFile5Reader` classes directly
=> Fix #149 replace `_read_mat` with `scipy.io.loadmat`

docs/_api/interp.rst, docs/api.rst, nitransforms/base.py, nitransforms/interp/bspline.py, nitransforms/nonlinear.py, nitransforms/tests/test_nonlinear.py
=> ENH: Base implementation of B-Spline transforms

.zenodo.json
See https://github.com/poldracklab/nitransforms/pull/151#issuecomment-1055802868
=> Add myself as a contributor

nitransforms/io/itk.py
=> FIX: Orientation of displacements field and header when reading ITK's h5

nitransforms/io/__init__.py, nitransforms/io/afni.py, nitransforms/io/base.py, nitransforms/io/fsl.py, nitransforms/io/itk.py, nitransforms/linear.py, nitransforms/tests/test_io.py, nitransforms/tests/test_linear.py
EAFP implementation of loading linear transforms without specifying the format of the file.
Resolves: #86.
Resolves: #87.
Resolves: #107.
=> ENH: Guess open linear transform formats

nitransforms/linear.py, nitransforms/manip.py, nitransforms/tests/test_manip.py
This PR makes the ``TransformChain`` class more consistent with the
overall coordinate system, assuming that transforms are chained with the
*points* criteria.
In other words, in the typical setup where we have estimated one
initializing affine and then perhaps two levels of nonlinear
deformations, when calculating the coordinates of a given index in the
reference image, the last nonlinear should be applied first, then the
second, and finally the affine to pull information from the moving
image.
In other words, the chaining (composition) operation works exactly as
a single transformation procedure.
Resolves #81.
=> ENH: API change in ``TransformChain`` - new composition convention

nitransforms/__init__.py, nitransforms/base.py, nitransforms/manip.py, nitransforms/nonlinear.py, nitransforms/tests/test_nonlinear.py
This PR lays the ground for future work on #56, and #89, by defining the matrix multiplication operator on field-based transforms.
=> ENH: Extend the nonlinear transforms API

nitransforms/nonlinear.py
Interpolate coordinates when the coordinates to be mapped fall off-grid of the field data array.
Closes: https://github.com/nipy/nitransforms/issues/155.
=> ENH: "Densify" voxel-wise nonlinear mappings with interpolation 

nitransforms/tests/test_base.py
Make sure the CIFTI2 file in the failing test is created with a ``float32`` data type.
Resolves: #177.
=> FIX: Ensure datatype of generated CIFTI2 file in ``TransformBase`` unit test

nitransforms/base.py
=> FIX: Set x-forms on resampled images

nitransforms/io/fsl.py, nitransforms/io/itk.py, nitransforms/linear.py, nitransforms/tests/test_linear.py
Resolves a bug that disabled loading ITK matlab files unless you used the low-level io utility.
=> ENH: Load ITK's ``.mat`` files with ``Affine``'s loaders

.github/workflows/pythonpackage.yml, .github/workflows/travis.yml, nitransforms/cli.py, nitransforms/io/lta.py, nitransforms/nonlinear.py, nitransforms/tests/test_io.py, nitransforms/tests/test_linear.py, nitransforms/tests/test_nonlinear.py, pyproject.toml, setup.cfg
Some additional cleanups. Not touching CircleCI right now, as it doesn't seem broken and it's at least testing 3.9.
Also ran `pyupgrade --py38-plus`. Automated housekeeping seems like a win.
=> MNT: Drop Python 3.7 support, test through 3.11

nitransforms/linear.py
This PR transforms the coordinates of the reference into the moving image for each timepoint separately, effectively minimizing the memory footprint.
Resolves: #173.
=> FIX: Postpone coordinate mapping on linear array transforms

nitransforms/base.py
`np.asanyarray(img.dataobj, img.get_data_dtype())` is almost never a great choice. `np.asanyarray(img.dataobj)` is intended to be conservative with its types, where either the original dtype is maintained or scaling is applied and the dtype becomes `float64`. The case where this fails in particular is when the on-disk dtype is `int16` with scale factors. If the scale factors send the data beyond the int16 range (slope > 1), then casting to int16 is going to truncate the data outside the range.
The approach here is to be pragmatic. We always use `np.asanyarray(img.dataobj)` to give the best estimate of the values in the data array that NIfTI can provide. If a dtype is provided, then we set both the output array and the image type to that, to avoid unnecessary copies and casting. If it is …
=> FIX: Remove unsafe cast during TransformBase.apply()

nitransforms/io/afni.py
As described in https://github.com/nipy/nitransforms/issues/158#issuecomment-2021670484, currently `_is_oblique` fails to detect certain oblique dataset. The reason (and fix) is very simple. Checking the implementation in AFNI (https://github.com/afni/afni/blob/b6a9f7a21c1f3231ff09efbd861f8975ad48e525/src/thd_coords.c#L689), the minimum across the three dimensions is computed before the arccos. However, in the implementation in nitransforms the minimum was computed after the arccos, which is incorrect--the max should be computed instead.
Example with the current PR:
```python
import numpy as np
from nitransforms.io.afni import _is_oblique, obliquity
affine = np.array([[ -0.5       ,   0.        ,   0.        ,  70.10167694],
[  0.        ,  -0.2254388 ,  -0.44629291, -36.50873947],
[  0. …
```
=> FIX _is_oblique

nitransforms/io/afni.py, nitransforms/io/base.py, nitransforms/io/fsl.py, nitransforms/io/itk.py
Write functions to output displacement fields from nitransforms to nifti for ITK/FSL/AFNI. 
see https://github.com/nipreps/niworkflows/pull/819#discussion_r1287485844
=> FIX: Output displacement fields

nitransforms/base.py
Before completely removing this, we should give downstream tools warnings to update.
=> ENH: Restore apply method, warning of deprecation and calling function

.github/workflows/pythonpackage.yml, nitransforms/io/afni.py, nitransforms/io/base.py, nitransforms/tests/test_cli.py, nitransforms/tests/test_version.py, setup.cfg
This a quick hack to get tests working.
We should purge `pkg_resources` and use `importlib.resources`, but I don't have the energy for that right now.
=> TEST: Fix tests for Python 3.12, numpy 2.0, and pytest-xdist

nitransforms/io/itk.py
Ports nipreps/fmriprep#3300 to nitransforms.
I've gotten ANTs to generate a warp field with a non-cardinal rotation matrix and anistropic spacing:
Need to verify that we're raveling the fixed parameters in the correct order. Numpy defaults to C.
=> FIX: Load ITK fields from H5 correctly

nitransforms/base.py
Related-to: #195.
Amends: #209.
=> FIX: Wrong warning argument name ``level`` in ``warnings.warn``

nitransforms/resampling.py, nitransforms/tests/test_base.py
Solves #214 , based off of PR #215 . A more complete draft for serialising 4D `apply()` to 3D+t is provided here. 
Intended to update branch [nipy:enh/reenable-parallelization-apply-214](https://github.com/nipy/nitransforms/tree/enh/reenable-parallelization-apply-214) before merging PR #215
=> ENH: reenable-parallelization-apply-214 (builds on PR #215, solves Issue #214)

env.yml
Before 2.5.3, conda would install the latest ITK (5.4 at the time of writing) but ants was linked against 5.3 and didn't pin that dependency.
In 2.5.3, ants was built and linked against 5.4 and I'm unaware of whether they properly pinned the dependency. Either way, this commit fixes both to 2.5.3 and 5.4.
=> MAINT: Update ANTs' pinnings

nitransforms/resampling.py
=> ENH: Implement a memory limitation mechanism in loading data

setup.cfg
With https://github.com/nipy/nitransforms/blob/f69faaf44a9cab39141df6f546394e862ed408d2/setup.cfg#L24 and [`pathlib` incorporated into the standard Python library](https://docs.python.org/3.8/library/pathlib.html) in v3.4, we should rely on the `pathlib` in the standard Python library, not [the unmaintained `pathlib` on PyPI intended for Python < 3.4](https://pypi.org/project/pathlib/).
Related: https://github.com/nipy/nitransforms/pull/203#discussion_r1747586808, https://github.com/nipy/nitransforms/pull/203#issuecomment-2334693880
=> FIX: Use standard library `pathlib`

.github/workflows/travis.yml, nitransforms/resampling.py
I'm honestly not sure why this isn't causing the current tests to fail, but it does cause sdcflows tests to fail: https://github.com/nipreps/sdcflows/actions/runs/10890546744/job/30219507551
=> PY39: Support pre-`__or__` types

nitransforms/manip.py, nitransforms/tests/test_linear.py
I believe 97727104 caused `TransforrmChain` to start treating `LinearTransformMapping`s as `Iterable`s to decompose. Thus, I was getting transform chains 303 transforms long instead of 4 long.
Here is a regression test that fails before the patch and passes after the patch.
I believe this resolves the issues in fMRIPrep/fMRIPost.
cc @tsalo
=> FIX: Do not treat iterable transforms as iterables of transforms when adding to a chain

nitransforms/__init__.py
This PR is for convenience after #195
=> RF: Add `resamping.apply` to top module imports

nitransforms/__init__.py, nitransforms/tests/test_version.py
There is no reasonable case where a user has pkg_resources-accessible metadata (or importlib-metadata) and does not have a `_version.py` file.
Instead of replacing with importlib-metadata, I'm just skipping ahead to the hard-coded "unknown", using `0+unknown` to satisfy PEP440.
There may be a very rare case where someone makes an editable installation and borks their directory, but knowing what the version was when they installed it won't help us a lot there.
=> fix: Remove pkg_resources dependency

nitransforms/resampling.py
When applying a 3D transform to a 4D image (intended: applying the same transform to every time slice), I get the following crash (relevant traceback only):
```
File "/home/corys/parcellate/parcellate/model.py", line 253, in sample
atlas_nii = nt.resampling.apply(
File "/home/corys/anaconda3/envs/meg/lib/python3.9/site-packages/nitransforms/resampling.py", line 277, in apply
resampled = asyncio.run(
File "/home/corys/anaconda3/envs/meg/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/home/corys/anaconda3/envs/meg/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
return future.result()
File "/home/corys/anaconda3/envs/meg/lib/python3.9/site-packages/nitransforms/resampling.py", line 111, in _apply_serial
xfm_t = transform …
```
=> Patch for crash when applying 3D transform to 4D image

CHANGES.rst, nitransforms/io/x5.py, nitransforms/nonlinear.py, nitransforms/tests/test_nonlinear.py
Extends support of nonlinear transforms to export/import X5 representation. New unit tests exercise the new I/O.
Cross-references: #241.
=> ENH: Add X5 support of nonlinear transforms

nitransforms/io/x5.py, nitransforms/linear.py, nitransforms/manip.py, nitransforms/nonlinear.py, nitransforms/tests/test_manip.py, nitransforms/tests/test_resampling.py
- Facilitates the reading of X5 transforms by adding a ``from_x5()`` function in the ``nitransforms.linear`` and ``nitransforms.nonlinear`` modules.
- Reading and writing of transform chains in X5 files, ensuring X5 files do not contain duplicated transforms.
- Ensures all individual transforms implement ``__eq__()``.
100% coverage of the patch.
=> ENH: X5 read/write support of ``TransformChain``

nitransforms/base.py, nitransforms/tests/test_base.py
=> FIX: Remove implementation of an abstract class

nitransforms/interp/bspline.py, nitransforms/nonlinear.py, nitransforms/tests/test_nonlinear.py
Mapping of individual coordinates (`BSplineFieldTransform.map()`) has been broken at least since #138.
This PR first created a test that confirmed the issue and then implemented a patch.
Resolves: #154.
=> FIX: BSpline mapping of individual points

nitransforms/tests/test_io.py
Adds some test cases (in particular, leveraging that provided by @feilong in #171) demonstrating the issues in the code. For now, tests are marked as xfail.
=> MNT: Add test cases demonstrating ordering bug reading composite ITK's HDF5 files

nitransforms/base.py, nitransforms/nonlinear.py, nitransforms/resampling.py, nitransforms/tests/test_base.py, nitransforms/tests/test_nonlinear.py, nitransforms/tests/test_resampling.py
Includes a critical hotfix for the ``ImageGrid.ndcoords`` property, which sometimes was overwritten (possibly in parallel tests?)
=> FIX: ``ImageGrid._coords`` was somehow overwritten + re-enable tests
